### ISSUE TITLE
discord.js v13 support

### ISSUE THREAD

**Issue by irfaantx** [ZickZenni/discord-booru#1]

**Comment by ZickZenni** [comment]
I'm sorry, but I stopped maintaining and updating discord-booru a long time ago.
I may try to create a better version, which isn't dependent of discord.js.

You still can use discord-booru, but not the **createEmbed** function. 
A post has these values: id, tags, author, compressed_file_url, original_file_url, rating and booru (from which booru is it coming from)
These will help you create your own embeds, that discord.js v13 is supporting.
I hope this will help you, making your bot.

Cheers!
